### ISSUE TITLE
FYI, few times per day

### ISSUE THREAD

**Issue by zhiliangpersonal** [gaodeng/Moon-FM-Issue#55]
```
Error: net::ERR_CONNECTION_TIMED_OUT
    at GenericProvider.getLatestVersion (C:\Users\zhiliang.liu\AppData\Local\Programs\moonfm\resources\app.asar\node_modules\electron-updater\src\providers\GenericProvider.ts:18:25)
    at C:\Users\zhiliang.liu\AppData\Local\Programs\moonfm\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:347:26
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at NsisUpdater.getUpdateInfoAndProvider (C:\Users\zhiliang.liu\AppData\Local\Programs\moonfm\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:336:43)
    at C:\Users\zhiliang.liu\AppData\Local\Programs\moonfm\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\zhiliang.liu\AppData\Local\Programs\moonfm\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:360:34)
    at NsisUpdater.checkForUpdates (C:\Users\zhiliang.liu\AppData\Local\Programs\moonfm\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:220:35)
    at NsisUpdater.checkForUpdatesAndNotify (C:\Users\zhiliang.liu\AppData\Local\Programs\moonfm\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:249:41)
    at App.<anonymous> (C:\Users\zhiliang.liu\AppData\Local\Programs\moonfm\resources\app.asar\dist\electron\main.js:1:10243)
    at App.emit (events.js:187:15)
```

---

Moon FM 0.2.2
Electron 4.2.0
win32 10.0.17763
Locale: en-US

**Comment by gaodeng** [comment]
hi,这个是由于你的网络连不上 moon.fm 导致的。请更新到最新版。https://moon.fm/
